"""Embed the GLSL kernels as strings for runtime compilation through the VapourSynth API.

The kernels used to be compiled to SPIR-V by glslc at build time and included as word arrays.
The core compiles GLSL itself (compileGPUShader, caching per core by source text), so the build
ships readable source instead and drops the external tool entirely.

Two things the core's compiler does not do, both settled here rather than at runtime:

  * there is no include handler, so `#include "common.glsl"` is resolved by substitution;
  * `#version` must lead the source, so it is stripped here and re-emitted by the caller ahead
    of the `#define PIXEL_TYPE n` preamble -- the only way a define can precede a kernel whose
    first line would otherwise have to be the version directive.

Everything else, notably the fact that common.glsl lands ahead of the `#extension` directives in
predict_cm.comp, reproduces exactly what glslc was already doing.
"""
import os
import sys

DELIM = 'NNEDI3GLSL'
VERSION_LINE = '#version 460'
INCLUDE_LINE = '#include "common.glsl"'


def ident(path):
    """pad.comp -> kPadSrc, predict_cm.comp -> kPredictCmSrc."""
    stem = os.path.splitext(os.path.basename(path))[0]
    return 'k' + ''.join(part.capitalize() for part in stem.split('_')) + 'Src'


def main():
    out_path, common_path, kernel_paths = sys.argv[1], sys.argv[2], sys.argv[3:]

    with open(common_path, encoding='utf-8') as f:
        common = f.read()
    if VERSION_LINE in common:
        sys.exit(f'{common_path}: the shared include must not carry a #version directive')

    chunks = ['/* Generated by embed_shaders.py -- edit the .comp files, not this. */\n',
              '#pragma once\n\n']
    for path in kernel_paths:
        with open(path, encoding='utf-8') as f:
            lines = f.read().splitlines(keepends=True)

        if not lines or lines[0].strip() != VERSION_LINE:
            sys.exit(f'{path}: expected {VERSION_LINE!r} as the first line')
        body = []
        for line in lines[1:]:
            body.append(common if line.strip() == INCLUDE_LINE else line)
        text = ''.join(body)

        if f'){DELIM}"' in text:
            sys.exit(f'{path}: contains the raw string delimiter )#{DELIM}"')
        chunks.append(f'inline constexpr char {ident(path)}[] = R"{DELIM}(\n{text}){DELIM}";\n\n')

    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(chunks))


if __name__ == '__main__':
    main()
